"""inc_m02_61_g52 acceso de usuarios a fincas (M:N)

Revision ID: 1b9536d4411c
Revises: 8acca3af329a
Create Date: 2026-09-23 23:30:00.000000

INC-M02-61-G52 (RF-41, RF-46; frontend #97). Cierra la deuda documentada en
``anotaciones/modulo_9/rf25_alcance_finca_multifinca_pendiente.md`` (fase F3 del
plan de control de acceso por BD).

El alcance por finca se resolvía con ``modulo9.fincas.id_usuario``: 1 finca = 1
dueño. Un Veterinario o un Ingeniero de Campo nunca es "dueño" de la finca que
atiende, así que su lista de fincas permitidas quedaba vacía y cada activo le
respondía 404, aunque tuviera el permiso de lectura. No había forma de asignarle
una finca ajena: asignarla a un segundo usuario respondía 409.

``modulo9.usuarios_fincas`` es la relación de acceso. ``fincas.id_usuario`` se
conserva como propietario (lo muestra el CRUD de fincas), pero deja de conceder
acceso por sí solo.

Sin ``idx_usuario_finca_usuario``: el índice de ``uq_usuario_finca`` ya empieza
por ``id_usuario`` y cubre esa búsqueda.
"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '1b9536d4411c'
down_revision: Union[str, Sequence[str], None] = '8acca3af329a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Columnas idénticas a las del baseline para poder usar CREATE OR REPLACE VIEW,
# que conserva los GRANT de la vista (un DROP + CREATE los pierde).
_VISTA_CONTEXTO = """
CREATE OR REPLACE VIEW modulo9.vw_rf25_contexto_usuario AS
 SELECT u.id_usuario,
    concat_ws(' '::text, u.nombre, u.apellidos) AS nombre_completo,
    r.id_rol,
    r.nombre_rol,
    f.id_finca,
    f.nombre AS finca_activa,
    (f.ubicacion ->> 'departamento'::text) AS departamento,
    f.es_activo AS finca_activa_estado,
    especies.especies_configuradas AS especies_en_finca
   FROM modulo1.usuarios u
     JOIN modulo1.roles r ON r.id_rol = u.id_rol
     {join_fincas}
     LEFT JOIN LATERAL ( SELECT COALESCE(array_agg(DISTINCT (e.nombre)::text ORDER BY (e.nombre)::text), ARRAY[]::text[]) AS especies_configuradas
           FROM (modulo9.umbrales_ambientales ua
             JOIN modulo9.especies e ON ((e.id_especie = ua.id_especie)))
          WHERE ((ua.es_activo IS TRUE) AND (e.es_activo IS TRUE))) especies ON (true)
"""

_JOIN_ACCESO = """LEFT JOIN (modulo9.usuarios_fincas uf
         JOIN modulo9.fincas f ON f.id_finca = uf.id_finca AND f.es_activo IS TRUE)
       ON uf.id_usuario = u.id_usuario AND uf.es_activo IS TRUE"""

_JOIN_DUENO = """LEFT JOIN modulo9.fincas f ON f.id_usuario = u.id_usuario AND f.es_activo IS TRUE"""


def upgrade() -> None:
    op.execute("""
        CREATE TABLE modulo9.usuarios_fincas (
            id_usuario_finca INTEGER GENERATED BY DEFAULT AS IDENTITY,
            id_usuario INTEGER NOT NULL,
            id_finca INTEGER NOT NULL,
            fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
            es_activo BOOLEAN NOT NULL DEFAULT true,
            CONSTRAINT usuarios_fincas_pkey PRIMARY KEY (id_usuario_finca),
            CONSTRAINT usuarios_fincas_id_usuario_fkey
                FOREIGN KEY (id_usuario)
                REFERENCES modulo1.usuarios (id_usuario)
                ON DELETE CASCADE ON UPDATE NO ACTION,
            CONSTRAINT usuarios_fincas_id_finca_fkey
                FOREIGN KEY (id_finca)
                REFERENCES modulo9.fincas (id_finca)
                ON DELETE CASCADE ON UPDATE NO ACTION,
            CONSTRAINT uq_usuario_finca UNIQUE (id_usuario, id_finca)
        )
    """)
    op.execute(
        "CREATE INDEX idx_usuario_finca_finca ON modulo9.usuarios_fincas (id_finca)"
    )
    op.execute("""
        COMMENT ON TABLE modulo9.usuarios_fincas IS
        'RF-25/RF-46: fincas a las que accede cada usuario sin alcance global. '
        'Varias personas pueden atender una misma finca (M:N).'
    """)
    # Conceder o retirar acceso a una finca es un cambio de seguridad: mismo
    # trigger genérico que ya llevan fincas y el resto de tablas del baseline.
    op.execute("""
        CREATE TRIGGER trg_auditoria
        AFTER INSERT OR DELETE OR UPDATE ON modulo9.usuarios_fincas
        FOR EACH ROW EXECUTE FUNCTION auditoria.fn_auditoria_dml()
    """)

    # Nadie pierde el acceso que ya tenía. El JOIN a usuarios descarta dueños
    # inexistentes: la FK de fincas.id_usuario es NOT VALID y puede tenerlos.
    op.execute("""
        INSERT INTO modulo9.usuarios_fincas (id_usuario, id_finca)
        SELECT f.id_usuario, f.id_finca
        FROM modulo9.fincas f
        JOIN modulo1.usuarios u ON u.id_usuario = f.id_usuario
    """)

    op.execute(_VISTA_CONTEXTO.format(join_fincas=_JOIN_ACCESO))


def downgrade() -> None:
    op.execute(_VISTA_CONTEXTO.format(join_fincas=_JOIN_DUENO))
    op.execute("DROP TABLE modulo9.usuarios_fincas")
