"""v5.3.0_rf49_compatibilidad_sensor_especie

Revision ID: 281e99d58ecb
Revises: 1d7d6069da52
Create Date: 2026-09-16 20:20:36.815429

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '281e99d58ecb'
down_revision: Union[str, Sequence[str], None] = '1d7d6069da52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # RF-49 / INC-M02-36-G85: el modelo de M09 no tenia una fuente de verdad
    # para decidir si un sensor podia asociarse a la especie de un activo. La
    # tabla funciona como lista blanca por sensor: una asociacion solo es
    # valida cuando existe el par (sensor, especie).
    op.execute("""
        CREATE TABLE modulo9.compatibilidad_sensores_especies (
            id_compatibilidad_sensor_especie INTEGER
                GENERATED BY DEFAULT AS IDENTITY,
            id_sensor INTEGER NOT NULL,
            id_especie INTEGER NOT NULL,
            fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT compatibilidad_sensores_especies_pkey
                PRIMARY KEY (id_compatibilidad_sensor_especie),
            CONSTRAINT compatibilidad_sensores_especies_id_sensor_fkey
                FOREIGN KEY (id_sensor)
                REFERENCES modulo9.sensores (id_sensores),
            CONSTRAINT compatibilidad_sensores_especies_id_especie_fkey
                FOREIGN KEY (id_especie)
                REFERENCES modulo9.especies (id_especie),
            CONSTRAINT uq_compatibilidad_sensor_especie
                UNIQUE (id_sensor, id_especie)
        )
    """)

    op.execute("""
        COMMENT ON TABLE modulo9.compatibilidad_sensores_especies IS
        'RF-49: lista blanca de especies biologicas compatibles por sensor IoT.'
    """)

    # Preserva el conocimiento que ya existe en M09 sin inferir especies a
    # partir del nombre o de la categoria fisico-quimica del sensor:
    #   1) especie explicita de la infraestructura donde esta instalado;
    #   2) especies permitidas por el tipo de esa infraestructura (RF-48).
    # UNION elimina duplicados cuando ambas fuentes expresan el mismo par.
    op.execute("""
        INSERT INTO modulo9.compatibilidad_sensores_especies (
            id_sensor,
            id_especie
        )
        SELECT saa.id_sensor, i.id_especie
        FROM modulo9.sensores_areas_asociadas saa
        JOIN modulo9.infraestructuras i
          ON i.id_infraestructura = saa.id_infraestructura
        WHERE saa.tiene_estado = TRUE
          AND i.id_especie IS NOT NULL

        UNION

        SELECT saa.id_sensor, c.id_especie
        FROM modulo9.sensores_areas_asociadas saa
        JOIN modulo9.infraestructuras i
          ON i.id_infraestructura = saa.id_infraestructura
        JOIN modulo9.tipos_area ta
          ON ta.nombre = i.tipo
        JOIN modulo9.compatibilidades_tipo_area_especie c
          ON c.id_tipo_area = ta.id_tipo_area
        WHERE saa.tiene_estado = TRUE
    """)


def downgrade() -> None:
    op.execute("DROP TABLE modulo9.compatibilidad_sensores_especies")
