"""fix: crea auditoria.intentos_fallidos (INC-M09-05-G115, RF-31, OWASP A09)

Revision ID: 62e45ebdb323
Revises: 56cd2038ff06
Create Date: 2026-09-06 17:19:57.230199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e45ebdb323'
down_revision: Union[str, Sequence[str], None] = '56cd2038ff06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE modulo9.intentos_fallidos (
            id_intento_fallido  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            entidad             VARCHAR(50)  NOT NULL,
            operacion           VARCHAR(20)  NOT NULL,
            codigo_error        VARCHAR(50)  NOT NULL,
            mensaje             TEXT         NOT NULL,
            campo               VARCHAR(100),
            payload             JSONB        NOT NULL,
            id_usuario          INTEGER,
            fecha_intento       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
            CONSTRAINT intentos_fallidos_id_usuario_fkey
                FOREIGN KEY (id_usuario)
                REFERENCES modulo1.usuarios (id_usuario)
                NOT VALID
        );

        CREATE INDEX idx_intentos_fallidos_entidad
            ON modulo9.intentos_fallidos (entidad, fecha_intento);
    """)

    op.execute("""
        COMMENT ON TABLE modulo9.intentos_fallidos IS
        'Registro de intentos fallidos de operaciones (creacion, actualizacion, etc.) que nunca llegaron a persistirse. Complementa a modulo9.logs_dml, que solo captura operaciones que si ocurrieron.';
    """)
    op.execute("""
        COMMENT ON COLUMN modulo9.intentos_fallidos.entidad IS
        'Nombre logico de la entidad sobre la que se intento operar, ej. plantilla, usuario.';
    """)
    op.execute("""
        COMMENT ON COLUMN modulo9.intentos_fallidos.codigo_error IS
        'Codigo de negocio del rechazo, ej. NOMBRE_PLANTILLA_DUPLICADO, ESPECIE_INACTIVA.';
    """)
    op.execute("""
        COMMENT ON COLUMN modulo9.intentos_fallidos.payload IS
        'Datos del intento rechazado (ej. el DTO recibido), para poder reconstruir que se intento hacer.';
    """)


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS modulo9.intentos_fallidos;")