"""Integracion RF-49 contra PostgreSQL con rollback exterior obligatorio.

Valida el rechazo por especie y el camino compatible usando el esquema real.
Si la migracion aun no esta desplegada, crea el catalogo dentro de la misma
transaccion que el fixture revierte al terminar.
"""
from __future__ import annotations

import pytest
from sqlalchemy import text

from src.biological_assets.application.use_cases.gestion.asociar_sensor_activo_use_case import (
    AsociarSensorActivoUseCase,
)
from src.biological_assets.infrastructure.adapters.infraestructura_m09_adapter import (
    InfraestructuraM09Adapter,
)
from src.biological_assets.infrastructure.adapters.sensor_m09_adapter import SensorM09Adapter
from src.biological_assets.infrastructure.dto.asociar_sensor_activo_dto import AsociarSensorActivoDTO
from src.biological_assets.infrastructure.repositories.activo_biologico_repository import (
    SqlAlchemyActivoBiologicoRepository,
)
from src.biological_assets.infrastructure.repositories.asociacion_sensor_activo_repository import (
    SqlAlchemyAsociacionSensorActivoRepository,
)
from src.identity_access.infrastructure.dependencies import UsuarioActual
from src.shared.errors import ValidationError

pytestmark = pytest.mark.integration


_CREAR_CATALOGO = """
CREATE TABLE IF NOT EXISTS modulo9.compatibilidad_sensores_especies (
    id_compatibilidad_sensor_especie INTEGER GENERATED BY DEFAULT AS IDENTITY,
    -- El rol member_dev no tiene privilegio REFERENCES. Las FKs pertenecen a
    -- la migracion real; este DDL transitorio solo habilita la prueba del
    -- adaptador y se revierte con la transaccion exterior.
    id_sensor INTEGER NOT NULL,
    id_especie INTEGER NOT NULL,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT compatibilidad_sensores_especies_pkey
        PRIMARY KEY (id_compatibilidad_sensor_especie),
    CONSTRAINT uq_compatibilidad_sensor_especie
        UNIQUE (id_sensor, id_especie)
)
"""


def _candidato_misma_finca(db_session):
    return db_session.execute(
        text(
            """
            SELECT
                a.id_activo_biologico,
                a.id_especie,
                e.nombre AS nombre_especie,
                a.tipo::text AS tipo_activo,
                a.id_infraestructura,
                a.id_usuario,
                s.id_sensores AS id_sensor,
                s.id_dispositivo_iot
            FROM modulo2.activos_biologicos a
            JOIN modulo9.especies e ON e.id_especie = a.id_especie
            JOIN modulo9.infraestructuras ia
              ON ia.id_infraestructura = a.id_infraestructura
            JOIN modulo9.sensores_areas_asociadas saa
              ON saa.tiene_estado = TRUE
            JOIN modulo9.infraestructuras sensor_area
              ON sensor_area.id_infraestructura = saa.id_infraestructura
             AND sensor_area.id_finca = ia.id_finca
            JOIN modulo9.sensores s
              ON s.id_sensores = saa.id_sensor
             AND s.es_activo = TRUE
            JOIN modulo9.dispositivos_iot d
              ON d.id_dispositivo_iot = s.id_dispositivo_iot
             AND d.es_activo = TRUE
            WHERE a.id_estado <> 6
              AND NOT EXISTS (
                  SELECT 1
                  FROM modulo2.asociaciones_activos_sensores aas
                  WHERE aas.id_sensor = s.id_sensores
                    AND aas.tipo = CAST('directa' AS modulo2.enum_asociaciones_activos_sensores_tipo)
                    AND aas.estado_asociacion = 'ACTIVA'
                    AND aas.fecha_fin IS NULL
              )
            ORDER BY a.id_activo_biologico, s.id_sensores
            LIMIT 1
            """
        )
    ).mappings().one_or_none()


def _configurar_unica_especie(db_session, id_sensor: int, id_especie: int) -> None:
    db_session.execute(
        text(
            "DELETE FROM modulo9.compatibilidad_sensores_especies "
            "WHERE id_sensor = :id_sensor"
        ),
        {"id_sensor": id_sensor},
    )
    db_session.execute(
        text(
            """
            INSERT INTO modulo9.compatibilidad_sensores_especies (id_sensor, id_especie)
            VALUES (:id_sensor, :id_especie)
            """
        ),
        {"id_sensor": id_sensor, "id_especie": id_especie},
    )
    db_session.flush()


def test_rechazo_y_asociacion_compatible_sin_residuos(db_session) -> None:
    db_session.execute(text(_CREAR_CATALOGO))
    candidato = _candidato_misma_finca(db_session)
    if candidato is None:
        pytest.skip("La base no contiene un activo y sensor activos dentro de la misma finca.")

    otra_especie = db_session.execute(
        text(
            """
            SELECT id_especie, nombre
            FROM modulo9.especies
            WHERE id_especie <> :id_especie
            ORDER BY es_activo DESC, id_especie
            LIMIT 1
            """
        ),
        {"id_especie": candidato["id_especie"]},
    ).mappings().one_or_none()
    if otra_especie is None:
        pytest.skip("La base requiere una segunda especie para probar incompatibilidad.")

    db_session.execute(
        text("SELECT set_config('app.usuario_id', :id_usuario, true)"),
        {"id_usuario": str(candidato["id_usuario"])},
    )

    repo = SqlAlchemyAsociacionSensorActivoRepository(db_session)
    use_case = AsociarSensorActivoUseCase(
        db=db_session,
        repo=repo,
        activo_repo=SqlAlchemyActivoBiologicoRepository(db_session),
        sensor_port=SensorM09Adapter(db_session),
        infra_port=InfraestructuraM09Adapter(db_session),
    )
    dto = AsociarSensorActivoDTO(
        tipo_activo=(
            'INDIVIDUAL' if candidato["tipo_activo"] == 'INDIVIDUAL' else 'LOTE'
        ),
        tipo_asociacion='DIRECTA',
        dispositivo_iot_id=candidato["id_dispositivo_iot"],
        sensor_id=candidato["id_sensor"],
        id_infraestructura=candidato["id_infraestructura"],
        motivo='Prueba RF-49 con rollback exterior',
    )
    usuario = UsuarioActual(
        id_usuario=candidato["id_usuario"],
        id_token=0,
        id_rol=1,
    )

    asociaciones_antes = db_session.execute(
        text(
            "SELECT COUNT(*) FROM modulo2.asociaciones_activos_sensores "
            "WHERE id_sensor = :id_sensor AND id_activo_biologico = :id_activo"
        ),
        {
            "id_sensor": candidato["id_sensor"],
            "id_activo": candidato["id_activo_biologico"],
        },
    ).scalar_one()

    _configurar_unica_especie(
        db_session,
        candidato["id_sensor"],
        otra_especie["id_especie"],
    )
    with pytest.raises(ValidationError) as exc:
        use_case.execute(candidato["id_activo_biologico"], dto, usuario)

    assert exc.value.code == 'INCOMPATIBILIDAD_ESPECIE_SENSOR'
    assert candidato["nombre_especie"] in exc.value.message
    assert otra_especie["nombre"] in exc.value.message
    assert db_session.execute(
        text(
            "SELECT COUNT(*) FROM modulo2.asociaciones_activos_sensores "
            "WHERE id_sensor = :id_sensor AND id_activo_biologico = :id_activo"
        ),
        {
            "id_sensor": candidato["id_sensor"],
            "id_activo": candidato["id_activo_biologico"],
        },
    ).scalar_one() == asociaciones_antes

    _configurar_unica_especie(
        db_session,
        candidato["id_sensor"],
        candidato["id_especie"],
    )
    creada = use_case.execute(candidato["id_activo_biologico"], dto, usuario)

    assert creada.id_asociacion_activo_sensor is not None
    assert creada.sensor_id == candidato["id_sensor"]
    assert creada.id_activo_biologico == candidato["id_activo_biologico"]
    assert db_session.execute(
        text(
            "SELECT COUNT(*) FROM modulo2.asociaciones_activos_sensores "
            "WHERE id_sensor = :id_sensor AND id_activo_biologico = :id_activo"
        ),
        {
            "id_sensor": candidato["id_sensor"],
            "id_activo": candidato["id_activo_biologico"],
        },
    ).scalar_one() == asociaciones_antes + 1
